### ISSUE TITLE
Issue: Exceeds expectations

### ISSUE THREAD

**Issue by emory** [jhne/norma#1]
I just wanted to leave a note to express how fantastic this theme of yours is. It's exceptional work and I was expecting the usual "hey look I'm using twitter bootstrap and grid jay ess whatever framework enjoy the helvetica" but I'm just unable to express anything other than my jaw dropping.

I hope it's OK that I'm playing with it on a test site and I'm completely enamored with it.

**Comment by jhne** [comment]
That's so nice to hear! It's getting some fixes and then I'll be releasing
it for real in just a few days. Do whatever you want with it!

söndag 15 mars 2015 skrev emory notifications@github.com:
