### ISSUE TITLE
Fråga ang menyn

### ISSUE THREAD

**Issue by BlackSkorpio** [jhne/norma#12]
Om jag vill ha menyn komprimerad på startsidan, hur bör jag gå tillväga isåfall?
Dum fråga, men jag suger på JS: minst sagt... :/

**Comment by jhne** [comment]
Kan skriva om lite så det enkelt går att ändra med en rad custom css.

**Comment by BlackSkorpio** [comment]
Kanon! :)

**Comment by BlackSkorpio** [comment]
Upptäckte precis din experimental branch!....

Menyn där, vad tror du om att lägga in den som val bland inställningarna för themat?

**Comment by jhne** [comment]
Bra idé. Ska jobba på det!

**Comment by BlackSkorpio** [comment]
Funderade lite på det...
(svårt att sova vissa nätter... ;) )

Om man lyfter ut all CSS som rör menyn i separata filer så kan man göra det till en inställningsmöjlighet...
För javascriptet kan ju ligga i samma fil och samsas med varandra...

**Comment by jhne** [comment]
Det ska gå och ordna med koken:if och lite pill i info.json. Håller på och testar så får vi se!

**Comment by jhne** [comment]
Detta kommer vara fixat i form av inställningar där man kan välja meny själv. Ny version kommer snart, tampas med category.lens och tag.lens just nu.
