### ISSUE TITLE
contents.lens läser inte in mer än 100 bilder

### ISSUE THREAD

**Issue by BlackSkorpio** [jhne/norma#14]
Detta är standard när man använder `<koken:load>`

Genom att använda: `<koken:load limit="18" infinite="true">`, så läses fler bilder in dynamiskt när besökaren när slutet på sidan

**Comment by jhne** [comment]
Fixat i nästa version som kommer snart.

**Comment by BlackSkorpio** [comment]
Kanon...
Har varit "lite" i farten med din kod jag med... ;)
