### ISSUE TITLE
Scale page (and essay) pictures to the with of the container

### ISSUE THREAD

**Issue by BlackSkorpio** [jhne/norma#4]
As it is now, pictures inserted to a page breaks the container and is 100% width of the browser window
Preview here:
http://varoystrand.se/preview.php?/sidor/testpage/&preview=norma

**Comment by BlackSkorpio** [comment]
Looks like it is solved be adding `.k-content-embed` to the style:
`.k-lens-page .page-content p, .k-lens-page .page-content h1 {
    max-width: 750px;
    margin: 0px auto;
    padding: 0px 20px;
}`

**Comment by jhne** [comment]
That is the idea from the beginning, to make it 100%. I will look into perhaps changing it though.

**Comment by BlackSkorpio** [comment]
I believe it would look better if images scale down to the width of the Container.
Looks more "aesthetic"
