### ISSUE TITLE
Bildtext

### ISSUE THREAD

**Issue by BlackSkorpio** [jhne/norma#5]
Caption/Beskrivning ser ut att hamna lite för långt ner under bilden:
http://varoystrand.se/preview.php?/sidor/testpage/&preview=norma
Och länken till "lightbox" syns inte:
http://varoystrand.se/preview.php?/sidor/about-me/&preview=norma
Under min "otroligt fina" porträttbild

**Comment by jhne** [comment]
Good catch, det borde fungera nu. Nummer två vet jag inte riktigt hur du menar, på vilket sätt ska länken synas? Lightboxen kickar in när man klickar på bilden.

**Comment by BlackSkorpio** [comment]
Glöm den biten, eftersom det var så mycket luft runt bilden så blir tomrummet mellan bild och "caption" klickbart: därför trodde jag att du lagt till en länk där...

**Comment by BlackSkorpio** [comment]
Har ändrat lite i min css som du säkert märkt när du kollat...

Är enligt min smak lite väl mycket luft mellan elementen... :/

**Comment by jhne** [comment]
Jag förstår dig, är däremot själv ett stort fan av marginaler och whitespace, tycker det ger ögonen en plats att vila och det blir lättare att fokusera på det man vill. Kul att se olika varianter däremot, är glad att du har gjort någonting med det! :)

**Comment by BlackSkorpio** [comment]
Ja, jag har svårt att låta bli att "pilla" på andras grejer ;) :+1: 
Speciellt när de redan är bra!... haha
