### ISSUE TITLE
album.description i album.lens

### ISSUE THREAD

**Issue by BlackSkorpio** [jhne/norma#7]
Att använda sig av {{ album.description paragraphs="true" }} istället för endast {{ album.description  }} gör att Koken tolkar radbrytningar i albumbeskrivningen så som användaren förväntar sig.

**Comment by jhne** [comment]
On it – blir lite strul med stylingen då men det kommer.

**Comment by BlackSkorpio** [comment]
Märkte det hos mig ;)
