### ISSUE TITLE
Pagination i album.lens

### ISSUE THREAD

**Issue by BlackSkorpio** [jhne/norma#8]
Kommer du lägga till stöd för "sidbrytning" i album.lens?
Användare med många bilder i sina album kan uppskatta detta...

**Comment by jhne** [comment]
Ja, funktionen att bara ladda in t.ex. 10 bilder till att börja med och mer när användaren har scrollat ner, det kommer läggas till.

**Comment by BlackSkorpio** [comment]
Kanon!
Låter bättre än standard funktionen med att klicka sig fram! :D
