### ISSUE TITLE
Suggestion: Bildnamn i album.lens

### ISSUE THREAD

**Issue by BlackSkorpio** [jhne/norma#9]
Ändra rad 31: `<koken:link lightbox="true">`
Till: `<koken:link title="{{ content.title | content.filename }}" lightbox="true">`

Kanske också lägga till en "overlay" med bildnamnet, så som du gjort för albumnamnet?
(Har gjort det på varoystrand.se om du vill se hur det blev: http://varoystrand.se/album/free-style/)

**Comment by jhne** [comment]
Väljer att ha den vanliga hovereffekten för att undvika eventuell förvirring (vad är album, vad är bild? etc).

**Comment by BlackSkorpio** [comment]
Det köper jag...
